language: python

matrix:
  include:
    - os: osx
      language: generic
      env:
        - TOXENV=py36
        - DEPLOY_FILE='dist/sqlitebiter_macos_amd64.tar.gz'

    - os: linux
      python: 3.6
      sudo: required
      env:
        - TOXENV=py36
        - DEPLOY_FILE='dist/sqlitebiter_*.deb'

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt -qq update ; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install -y fakeroot ; fi

install:
  - bash .travis/install.sh

script: 
  - tox

notifications:
  slack:
    secure: aXqewqb4rP4MrJoF0+pQjfke5/MW99YDq8qzWMy8DbafRZyqteQ18lt/lBjwI2SmP2ThH/IBsUwLKfug4tSPXZ5bgo9qygqRCSB5K/OfVlRsJ13EIm+QMiiGB2u6sZzemmIMkr7oQNTJK8QfhoAwfGUGcOQ/sVJu2iuLU9J6esJoQPzNdThpEEUhClCrYfECYUN6+eqc89G2QkFkK4wM93Z9HwpMyrLdSh3CqPEGz0pJY4FvzSzMewVkuJf02RyAHWKHPSvoNHa1g0kOzy2NW6ssfSzr7jO/lfCYS81hqsb6FfhYEad1CcjKaKXqQHr4c/ykfuyl/qkzCXH1F37/VJxYUMyk2DMRgLi8tWdgIyFnTTHVQF9uTBBnM3EuAQlgCrOtoCeZLNRGkqQ6dUuADT7J2+znoGunorj/dxZT1cAjroLyv2CmIpJHBTaq+DdDjfmMBxlC41CupwgmVX1/70Vb3PR9BDkODzWgiKn5SQeibIIKG94nKid1/VNzT+Hk7kdnq6iFxfK35nQloacw00Qyo1T05wpg8yIoJUAWl/H7EejVPwmHMqgvQ0Ve5uzW0ztEoUnRetAMZgOGiMeL98sW8dkIo1bNWo+y7APw7M08BvyY1lHiZdTtSnaag1mFm+ydBvI8up9VUdZwCn6sHeQDzDX+WHYbbl4AEvKG+xw=

# before_deploy:
  # - bash -x build_package.sh

# deploy:
  # provider: releases
  # skip_cleanup: true
  # api_key:
    # secure: "cMeMAo5Sot8OU4BZ+9LqQfN8MYNueQnyQfFzlkALIIjLJZk5bD4oA9CKRwi33pVpwq+XlDa8Sok/CTZXYQ/b7cExZuW/pYVGwk+oNLxM5wfT1jU3nWfvymykKU6U/Lv9i2MsZiPWbciDzzBg9WAEicSCEi1Qh/mKYiPvF8F5AmSVQnEtXwhR6xbbOuJDd2zLLEuJFKtmP9hq7CPAmUksT6brIHDaVyaF8BH7Zd12KCbZlPtuNe+biDPPUwFJj+lLgtG29mO0nrulS9/E/LcDKnlQ0SJDMB8+I3EuVh+ftW/+ExgN5eSC9p6SLDlzMfpY3tHBywhWkhCviiRmKoP99eKnM33zix6UxKvc6E8ewwAoZfjhCo4jPkTDHVs43lJV1aVMcyaXtLWJwij3Q0EZRy+wH8rumvkK30r8lPvQ2UOi0y/Py22Jkj/VbewYuO7NTH1S6why0vPQEL1RlbxG3RXSM3MiUCspDTwedGvvfrHUrWcZXJB+44J1kD/eWBWB5RwLR5HBlSRgJ1+H5RpnQovCkgydM1DECjsxBFy6Xs1SwpnZ5SSYmfZTzy3SSb2KVd1uzvpko6kwranE5ccPdSzxfnVYT+08/q9It34gHfdBsmdXu4LDNxmAROFHlmekQ0xHY9qn8cpuTvjxmqpYjIZHcGNV8UaxjkqIhv0BpB4="
  # file_glob: true
  # file: $DEPLOY_FILE
  # on:
    # tags: false
    # branch: master
