language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=python2.7
    - python: 3.6
      env: TOXENV=python3.6

os:
  - linux

install:
  - pip install tox

script: 
  - tox
  - bash packaging.sh

notifications:
  slack:
    secure: aXqewqb4rP4MrJoF0+pQjfke5/MW99YDq8qzWMy8DbafRZyqteQ18lt/lBjwI2SmP2ThH/IBsUwLKfug4tSPXZ5bgo9qygqRCSB5K/OfVlRsJ13EIm+QMiiGB2u6sZzemmIMkr7oQNTJK8QfhoAwfGUGcOQ/sVJu2iuLU9J6esJoQPzNdThpEEUhClCrYfECYUN6+eqc89G2QkFkK4wM93Z9HwpMyrLdSh3CqPEGz0pJY4FvzSzMewVkuJf02RyAHWKHPSvoNHa1g0kOzy2NW6ssfSzr7jO/lfCYS81hqsb6FfhYEad1CcjKaKXqQHr4c/ykfuyl/qkzCXH1F37/VJxYUMyk2DMRgLi8tWdgIyFnTTHVQF9uTBBnM3EuAQlgCrOtoCeZLNRGkqQ6dUuADT7J2+znoGunorj/dxZT1cAjroLyv2CmIpJHBTaq+DdDjfmMBxlC41CupwgmVX1/70Vb3PR9BDkODzWgiKn5SQeibIIKG94nKid1/VNzT+Hk7kdnq6iFxfK35nQloacw00Qyo1T05wpg8yIoJUAWl/H7EejVPwmHMqgvQ0Ve5uzW0ztEoUnRetAMZgOGiMeL98sW8dkIo1bNWo+y7APw7M08BvyY1lHiZdTtSnaag1mFm+ydBvI8up9VUdZwCn6sHeQDzDX+WHYbbl4AEvKG+xw=

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "V9VRlKW0watv3I0yLi/nMh2+eA+wkj2pibq+XcnstD0W0DzMGuUu83YCQNiTZLvi4m/BWOrA6w+eNlJPeyI3CX8T/hY5C8+uaNmJSaAIVhWLSSo8CbLyLixRO9sVSM5rjell1IYdPtE/mTWmnvMv/zEQ5yNfY6+XT5OeehoxT0421OfH8KtqEhGYh7ZWlEjlAxdTdQptkAOjBB2IAAuCGmtTvPDxoq27xbkYtgB1NeE7NuSU6Ba4+tHTfbVmjiQc7e0CffBCvCHs2zpkU3D7lhNvr9X77c+KgR0KBz4rOjmB7iM486zAcWo6YLO6774GuOrwiemBOqQ8x/4WPnWabU6uXYHf5Km7jSjiCdI5vfTGRG9z7471ORLm4Nd+oyPtrcW0sW4c6V6DKH2+p8OBoH3sRVa0iroTqiG4WK7Ffc4EzxqxDH+1xQydpXTSTuroKBGuYnWXvl34Llh33O0ksL9Q6sUDFh+LXHNDEIQoqZfBx6Nv2vHyDrdsPowy9JR05eeAmInbMTYB3P80hZpd3bRrk4ZufMvMVeVXeJCfhsah8Ob8iTYfBzhnSID7jaTBcmEcgBH7czWJI0RwSKUPK6oDWHSsztBNJhixy+9FE4P5cHg4WYLQf8/1y/+khNTf4noS63NOCNYYct88dAxzXjJFtd5687VK53ZF/LLPsJw="
  file: 
    - tcconfig_wheel.tar.gz
  on:
    tags: false
