build: false
environment:
    matrix:
        - PYTHON: "C:/Python27-x64"
        - PYTHON: "C:/Python36-x64"

configuration:
    - Test
    - Release

init:
    - "ECHO %PYTHON%"
    - ps: "ls C:/Python*"

install:
    - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
    - "%PYTHON%/python.exe C:/get-pip.py"
    - "%PYTHON%/Scripts/pip.exe --version"

notifications:
  - provider: Slack
    auth_token:
      secure: JyTQAtBzpPYiWK3eRTz/U+rvmAKopqIWE19ti4vSL/IRygV3jUVUkwET1VyTlrqOeYfNx3Kfcp7eUmHCHxFCgw==
    channel: notifications

matrix:
  exclude:
    - configuration: Release
      PYTHON: "C:/Python27-x64"

for:
  -
    matrix:
      only:
        - configuration: Test

    install:
        - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
        - "%PYTHON%/python.exe C:/get-pip.py"
        - "%PYTHON%/Scripts/pip.exe --version"
        - "%PYTHON%/Scripts/pip.exe install .[test]"

    test_script:
        - "%PYTHON%/python.exe invoke_pytest.py"

  -
    matrix:
      only:
        - configuration: Release
          PYTHON: "C:/Python27-x64"
    before_deploy:
        - "%PYTHON%/Scripts/pip.exe install .[gs,mediawiki,build] jsonschema==2.6.0"
        - "build_win_package.bat"
        - ps: appveyor PushArtifact dist/sqlitebiter_win_x64.zip
    deploy:
    - provider: GitHub
      tag: $(APPVEYOR_REPO_TAG_NAME)
      description: 'Release description'
      auth_token:
        secure: yCkrIbtWpwkayosMqpLMv0ew4Le1PY0kYBMNlOIbD6jwSRnc5dRhV6n9DAGMqQ0f
      draft: false
      prerelease: true
      on:
        appveyor_repo_tag: true        # deploy on tag push only
