build: false
environment:
  matrix:
    - PYTHON: "C:/Python36-x64"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON%/Scripts/pip.exe --version"
  - "%PYTHON%/Scripts/pip.exe install -r requirements/requirements.txt"
  - "%PYTHON%/Scripts/pip.exe install -r requirements/build_requirements.txt"

test_script:
  - "echo a"

notifications:
  - provider: Slack
    auth_token:
      secure: JyTQAtBzpPYiWK3eRTz/U+rvmAKopqIWE19ti4vSL/IRygV3jUVUkwET1VyTlrqOeYfNx3Kfcp7eUmHCHxFCgw==
    channel: notifications

before_deploy:
  - "packaging.bat"

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: cMeMAo5Sot8OU4BZ+9LqQfN8MYNueQnyQfFzlkALIIjLJZk5bD4oA9CKRwi33pVpwq+XlDa8Sok/CTZXYQ/b7cExZuW/pYVGwk+oNLxM5wfT1jU3nWfvymykKU6U/Lv9i2MsZiPWbciDzzBg9WAEicSCEi1Qh/mKYiPvF8F5AmSVQnEtXwhR6xbbOuJDd2zLLEuJFKtmP9hq7CPAmUksT6brIHDaVyaF8BH7Zd12KCbZlPtuNe+biDPPUwFJj+lLgtG29mO0nrulS9/E/LcDKnlQ0SJDMB8+I3EuVh+ftW/+ExgN5eSC9p6SLDlzMfpY3tHBywhWkhCviiRmKoP99eKnM33zix6UxKvc6E8ewwAoZfjhCo4jPkTDHVs43lJV1aVMcyaXtLWJwij3Q0EZRy+wH8rumvkK30r8lPvQ2UOi0y/Py22Jkj/VbewYuO7NTH1S6why0vPQEL1RlbxG3RXSM3MiUCspDTwedGvvfrHUrWcZXJB+44J1kD/eWBWB5RwLR5HBlSRgJ1+H5RpnQovCkgydM1DECjsxBFy6Xs1SwpnZ5SSYmfZTzy3SSb2KVd1uzvpko6kwranE5ccPdSzxfnVYT+08/q9It34gHfdBsmdXu4LDNxmAROFHlmekQ0xHY9qn8cpuTvjxmqpYjIZHcGNV8UaxjkqIhv0BpB4=
  artifact: dist/sqlitebiter_win_x64.zip
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only
